### ISSUE TITLE
Cache-Control Header Missing

### ISSUE THREAD

**Issue by circlesmiler** [mmajis/plantuml-serverless#14]
If the service is used from a browser, the diagram images could be cached. But there is no `Cache-Control` header in the response. So, the caching is very short or disabled, even if the diagram can not be different as before, right?

**Comment by mmajis** [comment]
Hi @circlesmiler! 

You’re right, looks like caching could be improved. I’ll add cache control with one year max age at some point. 

Thanks!

**Comment by mmajis** [comment]
Fixed with f5e197ef57ce8edab1d429888e0024bcc527f1fb and available on v0.0.9
