### ISSUE TITLE
How to use plantuml API

### ISSUE THREAD

**Issue by jiawei686** [mmajis/plantuml-serverless#19]
After deploying the serverless code, I know it's useful for vscode plugin. But can I use serverless plantuml api to render graph in my own app?

**Comment by mmajis** [comment]
Hi! @jiawei686!

The serverless API is intended as a drop-in replacement for PlantUML Server. The API is described here: https://plantuml.com/server. You'll need to do the following to your diagram text content to send it over correctly:

1. Encode in UTF-8
2. Compress using Deflate or Brotli algorithm
3. Re-encode in ASCII using a transformation _close to_ base64 (this is a bit messy)
    * There's an implementation in JS here: https://github.com/mmajis/plantuml-serverless/blob/master/ui/index.html#L1740
    * And in Java here: https://github.com/plantuml/plantuml/blob/bc1074a7758e80c523aa51c4665fc23949827980/src/net/sourceforge/plantuml/code/AsciiEncoder.java
4. Send a GET request to one of the paths which specify the response format, e.g. /png/<ENCODED_CONTENT>

More discussion on the encoding here: https://plantuml.com/text-encoding

**Comment by jiawei686** [comment]
Got it! Thanks a lot!
