### ISSUE TITLE
awslib version

### ISSUE THREAD

**Issue by easypeasydigital** [mmajis/plantuml-serverless#20]
the plantUml standard lib includes an old version of awslib.  This package had an even older version.  It is possible to get it up to date?

**Comment by mmajis** [comment]
There's now a new version `1.2021.10` of plantuml which contains the latest awslib icon set. [v0.2.0](https://github.com/mmajis/plantuml-serverless/tree/v0.2.0) of plantuml-serverless bundles this new version of plantuml.

The awslib icon set was upgraded from version 7.0.0 to 10.0.0.

Enjoy! :)
