### ISSUE TITLE
UI?

### ISSUE THREAD

**Issue by freiit** [mmajis/plantuml-serverless#3]
Hi, really like what you did here :-)

Would it be possible to release also the UI as a function?
It seems its almost done, but I'm lacking some knowledge to do it myself...

Thanks :)

**Comment by mmajis** [comment]
Thanks!

Yes, I’ll set up the UI soon. I didn’t get a chance today to make the release with the UI but I’ll try to get back to it within a week or so.

In the meantime I’ll be happy to merge a pull request if you figure it out :)

**Comment by mmajis** [comment]
Ok @freiit now there's a new version 0.0.4 with UI. See here for example: https://plantuml.nitorio.us/

Deploy from https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:293246570391:applications~plantuml-render 

👍

**Comment by freiit** [comment]
Thank you very much! That FE looks great :-) (Re)Installation worked without issues.
